[package]
name = "eccodes-sys"
version = "0.1.0"
edition = "2018"

[features]
tests = []
nobuild = []
build_source = []
shared = ["build_source"]
no_memfs = ["build_source"]
jpeg = ["build_source"]
png = ["build_source"]
posix = ["build_source"]
netcdf = ["build_source"]

[build-dependencies]
bindgen = "0.58.1"
pkg-config = "0.3.19"
cmake = "0.1.45"
