[package]
name = "eccodes-sys"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
bindgen = "0.58.1"
pkg-config = "0.3.19"
cmake = "0.1.45"
