name: cargo

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Prepare environment
      run: |
        sudo apt-get update
        sudo apt-get install clang
        sudo apt-get install libclang1
        sudo apt-get install libeccodes-dev
        cargo clean
    - name: Build with existing library
      run: |
        cargo build
        cargo clean
    - name: Build default and test
      run: |
        cargo test --features "tests"  
