name: cargo

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Prepare environment
      run: |
        sudo apt-get update
        sudo apt-get install clang
        sudo apt-get install libclang1
        cargo clean
    - name: Build with existing library
      run: |
        sudo apt-get install libeccodes-dev
        cargo build
        cargo clean
        sudo apt-get remove libeccodes-dev
        sudo apt-get autoremove
    - name: Build shared without memfs
      run: |
        cargo build --features "shared no_memfs"
        cargo clean
    - name: Build shared with memfs
      run: |
        cargo build --features "shared"
        cargo clean
    - name: Build static without memfs
      run: |
        cargo build --features "build_source no_memfs"
        cargo clean
    - name: Build static with memfs
      run: |
        cargo build --features "build_source"
        cargo clean
    - name: Build with jpeg
      run: |
        sudo apt-get install libopenjp2-7-dev
        cargo build --features "build_source jpeg"
        cargo clean
    - name: Build static with png
      run: |
        sudo apt-get install libpng-dev
        cargo build  --features "build_source png"
        cargo clean
    - name: Build static with netcdf
      run: |
        sudo apt-get install libnetcdff-dev libnetcdf-c++4-dev
        cargo build --features "build_source netcdf"
        cargo clean
    - name: Build static with posix threads
      run: |
        cargo build --features "build_source posix"
        cargo clean
    - name: Build static with aec
      run: |
        sudo apt-get install libaec-dev
        cargo build --features "build_source aec"
        cargo clean
    - name: Build default and test
      run: |
        cargo build --features "tests"
        cargo test       
